/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Public, no database access.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Public. Demo accounts and the demo password only when DEMO_MODE=true.
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Sets the httpOnly session cookie. Rate limited per (client IP, email).
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Always 204; clears the cookie whether or not a session existed.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get World */
        get: operations["get_world_api_world_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_api_me_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classes */
        get: operations["list_classes_api_teacher_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher/classes/{class_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Class Progress
         * @description That class's teacher or an admin; another teacher's class is 404 (not 403).
         */
        get: operations["class_progress_api_teacher_classes__class_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/missions/{mission_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Attempt
         * @description Start the mission, or return the OPEN attempt (200) so a finished run can be submitted.
         */
        post: operations["start_attempt_api_missions__mission_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attempt
         * @description The current StateView: how a student resumes after a reload or a lost connection.
         */
        get: operations["get_attempt_api_attempts__attempt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance
         * @description CONTINUE on a narrative or consequence node; node_id must be the current node.
         */
        post: operations["advance_api_attempts__attempt_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer
         * @description Lock the checkpoint's answer; the server grades it. No outcome field (F-01).
         */
        post: operations["answer_api_attempts__attempt_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit
         * @description Two-phase and idempotent: grade once, then Maya's feedback. Returns the Report.
         */
        post: operations["submit_api_attempts__attempt_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_attempts__attempt_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvanceRequest */
        AdvanceRequest: {
            /** Node Id */
            node_id: string;
        };
        /** AnswerRequest */
        AnswerRequest: {
            /** Node Id */
            node_id: string;
            /** Option Id */
            option_id?: string | null;
            /** Text */
            text?: string | null;
        };
        /**
         * AnswerResponse
         * @description No outcome / is_correct field (F-01): the story carries what happened.
         */
        AnswerResponse: {
            /** Maya Line */
            maya_line: string | null;
            state: components["schemas"]["StateView"];
        };
        /** AttemptRecord */
        AttemptRecord: {
            /** Attempt Number */
            attempt_number: number;
            /** Started At */
            started_at: string;
            /** Submitted At */
            submitted_at: string;
            ending: components["schemas"]["EndingRef"];
            /** Story Minutes Used */
            story_minutes_used: number;
            /** Rescue Used */
            rescue_used: boolean;
            /** Hints Received */
            hints_received: number;
        };
        /** AudioStimulus */
        AudioStimulus: {
            /**
             * Kind
             * @constant
             */
            kind: "audio";
            /** Speaker */
            speaker: string | null;
            /** Audio Script */
            audio_script: string;
            /** Rate */
            rate: number;
            /** Text */
            text?: null;
        };
        /** CefrRange */
        CefrRange: {
            /**
             * Min
             * @enum {string}
             */
            min: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /**
             * Max
             * @enum {string}
             */
            max: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
        };
        /** CheckpointView */
        CheckpointView: {
            /** Item Id */
            item_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "multiple_choice" | "fill_blank" | "comprehension" | "vocabulary";
            /** Prompt */
            prompt: string;
            /** Stimulus */
            stimulus: components["schemas"]["AudioStimulus"] | components["schemas"]["TextStimulus"] | null;
            /** Options */
            options: components["schemas"]["OptionView"][] | null;
        };
        /** ClassProgressResponse */
        ClassProgressResponse: {
            /** Class Id */
            class_id: string;
            /** Name */
            name: string;
            /** Students */
            students: components["schemas"]["ClassStudent"][];
        };
        /** ClassStudent */
        ClassStudent: {
            /** Display Name */
            display_name: string;
            /** Missions Played */
            missions_played: number;
            /** Latest Label */
            latest_label: string | null;
            profile: components["schemas"]["Profile"] | null;
            /** Last Activity At */
            last_activity_at: string | null;
        };
        /** ClassSummary */
        ClassSummary: {
            /** Class Id */
            class_id: string;
            /** Name */
            name: string;
            /** Teacher Name */
            teacher_name: string;
            /** Student Count */
            student_count: number;
        };
        /** ClassesResponse */
        ClassesResponse: {
            /** Classes */
            classes: components["schemas"]["ClassSummary"][];
        };
        /** Clock */
        Clock: {
            /** Time */
            time: string;
            /** Minutes Left */
            minutes_left: number;
            /** Train Departed */
            train_departed: boolean;
            /** Label */
            label: string;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Demo Mode */
            demo_mode: boolean;
            /** Demo Accounts */
            demo_accounts: components["schemas"]["DemoAccount"][] | null;
            /** Demo Password */
            demo_password: string | null;
        };
        /** DemoAccount */
        DemoAccount: {
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "teacher" | "admin";
            /** Purpose */
            purpose: string;
        };
        /** DiaryCheckpoint */
        DiaryCheckpoint: {
            /** Item Id */
            item_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "multiple_choice" | "fill_blank" | "comprehension" | "vocabulary";
            /**
             * Skill
             * @enum {string}
             */
            skill: "grammar" | "vocabulary" | "reading" | "listening" | "speaking";
            /**
             * Cefr
             * @enum {string}
             */
            cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "understood" | "missed";
        };
        /** DiaryEntryView */
        DiaryEntryView: {
            /** Seq */
            seq: number;
            /** Clock */
            clock: string;
            /** Node Id */
            node_id: string;
            /** Kind */
            kind: string;
            /** Location */
            location: string;
            /** Text */
            text: string;
            checkpoint: components["schemas"]["DiaryCheckpoint"] | null;
            /**
             * Maya Decision
             * @enum {string}
             */
            maya_decision: "quiet" | "hint" | "rescue";
        };
        /** EndingRef */
        EndingRef: {
            /** Key */
            key: string;
            /** Title */
            title: string;
        };
        /** FeedbackSource */
        FeedbackSource: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "fallback";
            /** Provider Label */
            provider_label: string;
        };
        /** Greeting */
        Greeting: {
            /** Text */
            text: string;
            /**
             * Source
             * @enum {string}
             */
            source: "first_meeting" | "memory";
            /**
             * Mood
             * @enum {string}
             */
            mood: "curious" | "encouraging" | "worried" | "proud";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HistoryRow */
        HistoryRow: {
            /** Attempt Id */
            attempt_id: string;
            /** Attempt Number */
            attempt_number: number;
            /** Mission Id */
            mission_id: string;
            /** Mission Title */
            mission_title: string;
            /** Submitted At */
            submitted_at: string;
            ending: components["schemas"]["EndingRef"];
            /** Label */
            label: string;
            /**
             * Suggested Cefr
             * @enum {string}
             */
            suggested_cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /** Score Pct */
            score_pct: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Skills */
            skills: components["schemas"]["SkillScore"][];
        };
        /** Interpretation */
        Interpretation: {
            /** Summary */
            summary: string;
            /**
             * Strength
             * @enum {string}
             */
            strength: "grammar" | "vocabulary" | "reading" | "listening" | "speaking";
            /**
             * Challenge
             * @enum {string}
             */
            challenge: "grammar" | "vocabulary" | "reading" | "listening" | "speaking";
            /** Recommendation */
            recommendation: string;
        };
        /** LatestResult */
        LatestResult: {
            /** Attempt Id */
            attempt_id: string;
            /** Label */
            label: string;
            /** Submitted At */
            submitted_at: string;
        };
        /** LevelEvidence */
        LevelEvidence: {
            /**
             * Cefr
             * @enum {string}
             */
            cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /** Correct */
            correct: number;
            /** Total */
            total: number;
            /** Required */
            required: number;
            /** Met */
            met: boolean;
        };
        /** LevelPoint */
        LevelPoint: {
            /** Attempt Id */
            attempt_id: string;
            /** Submitted At */
            submitted_at: string;
            /**
             * Suggested Cefr
             * @enum {string}
             */
            suggested_cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MayaView */
        MayaView: {
            /**
             * Mood
             * @enum {string}
             */
            mood: "curious" | "encouraging" | "worried" | "proud";
            /**
             * Decision
             * @enum {string}
             */
            decision: "quiet" | "hint" | "rescue";
            /** Line */
            line: string | null;
        };
        /** MissedCheckpoint */
        MissedCheckpoint: {
            /** Item Id */
            item_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "multiple_choice" | "fill_blank" | "comprehension" | "vocabulary";
            /**
             * Skill
             * @enum {string}
             */
            skill: "grammar" | "vocabulary" | "reading" | "listening" | "speaking";
            /**
             * Cefr
             * @enum {string}
             */
            cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /** Prompt */
            prompt: string;
            /** Stimulus */
            stimulus: components["schemas"]["AudioStimulus"] | components["schemas"]["TextStimulus"] | null;
            /** Your Answer */
            your_answer: string;
            /** Correct Answer */
            correct_answer: string;
            /** Explanation */
            explanation: string;
            /** Maya Tip */
            maya_tip: string;
        };
        /** MissionCard */
        MissionCard: {
            /** Mission Id */
            mission_id: string;
            /** Title */
            title: string;
            /** World Zone */
            world_zone: string;
            /** Teaser */
            teaser: string;
            /** Sort Order */
            sort_order: number;
            /** Skill Focus */
            skill_focus: ("grammar" | "vocabulary" | "reading" | "listening" | "speaking")[];
            cefr_range: components["schemas"]["CefrRange"];
            /** Playable */
            playable: boolean;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "in_progress" | "waiting_to_submit" | "completed" | "locked" | "in_preparation";
            /** Is Maya Pick */
            is_maya_pick: boolean;
            /** Unlock Hint */
            unlock_hint: string;
            open_attempt: components["schemas"]["OpenAttemptCard"] | null;
            latest_result: components["schemas"]["LatestResult"] | null;
            /** Attempts Submitted */
            attempts_submitted: number;
        };
        /** NextMission */
        NextMission: {
            /** Mission Id */
            mission_id: string;
            /** Title */
            title: string;
            /** Skill Focus */
            skill_focus: ("grammar" | "vocabulary" | "reading" | "listening" | "speaking")[];
            /** Reason */
            reason: string;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "in_progress" | "waiting_to_submit" | "completed" | "locked" | "in_preparation";
            /** Unlock Hint */
            unlock_hint: string;
        };
        /** NodeView */
        NodeView: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "narrative" | "checkpoint" | "consequence" | "ending";
            scene: components["schemas"]["SceneView"];
            checkpoint: components["schemas"]["CheckpointView"] | null;
            ending: components["schemas"]["EndingRef"] | null;
        };
        /** Note */
        Note: {
            /** Text */
            text: string;
            /** Created At */
            created_at: string;
        };
        /** OpenAttemptCard */
        OpenAttemptCard: {
            /** Attempt Id */
            attempt_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "completed";
            clock: components["schemas"]["Clock"];
            /** Location */
            location: string;
            ending: components["schemas"]["EndingRef"] | null;
        };
        /** OptionView */
        OptionView: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** Profile */
        Profile: {
            /** Based On Attempts */
            based_on_attempts: number;
            /** Skills */
            skills: components["schemas"]["SkillPct"][];
        };
        /** ProgressOpenAttempt */
        ProgressOpenAttempt: {
            /** Attempt Id */
            attempt_id: string;
            /** Mission Id */
            mission_id: string;
            /** Mission Title */
            mission_title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "completed";
            clock: components["schemas"]["Clock"];
        };
        /** ProgressResponse */
        ProgressResponse: {
            profile: components["schemas"]["Profile"] | null;
            /** History */
            history: components["schemas"]["HistoryRow"][];
            /** Level History */
            level_history: components["schemas"]["LevelPoint"][];
            /** Notes */
            notes: components["schemas"]["Note"][];
            open_attempt: components["schemas"]["ProgressOpenAttempt"] | null;
        };
        /** Report */
        Report: {
            /** Attempt Id */
            attempt_id: string;
            /** Mission Id */
            mission_id: string;
            /** Mission Title */
            mission_title: string;
            /** Label */
            label: string;
            result: components["schemas"]["ResultBlock"];
            attempt_record: components["schemas"]["AttemptRecord"];
            interpretation: components["schemas"]["Interpretation"];
            feedback_source: components["schemas"]["FeedbackSource"];
            next_mission: components["schemas"]["NextMission"] | null;
            /** Diary */
            diary: components["schemas"]["DiaryEntryView"][];
            /** Missed */
            missed: components["schemas"]["MissedCheckpoint"][];
        };
        /** ResultBlock */
        ResultBlock: {
            /** Score Pct */
            score_pct: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Total */
            total: number;
            /** Skills */
            skills: components["schemas"]["SkillScore"][];
            /** Unmeasured Skills */
            unmeasured_skills: ("grammar" | "vocabulary" | "reading" | "listening" | "speaking")[];
            suggested_level: components["schemas"]["SuggestedLevel"];
        };
        /** SceneLine */
        SceneLine: {
            /** Speaker */
            speaker: string;
            /** Text */
            text: string;
        };
        /** SceneView */
        SceneView: {
            /** Location */
            location: string;
            /** Backdrop */
            backdrop: string;
            /** Lines */
            lines: components["schemas"]["SceneLine"][];
        };
        /** SkillPct */
        SkillPct: {
            /**
             * Skill
             * @enum {string}
             */
            skill: "grammar" | "vocabulary" | "reading" | "listening" | "speaking";
            /** Pct */
            pct: number;
        };
        /** SkillScore */
        SkillScore: {
            /**
             * Skill
             * @enum {string}
             */
            skill: "grammar" | "vocabulary" | "reading" | "listening" | "speaking";
            /** Correct */
            correct: number;
            /** Total */
            total: number;
            /** Pct */
            pct: number;
        };
        /** Snapshot */
        Snapshot: {
            /** Missions Played */
            missions_played: number;
            /** Latest Label */
            latest_label: string | null;
            profile: components["schemas"]["Profile"] | null;
        };
        /** StateView */
        StateView: {
            /** Attempt Id */
            attempt_id: string;
            /** Mission Id */
            mission_id: string;
            /** Mission Title */
            mission_title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "in_progress" | "completed" | "submitted";
            clock: components["schemas"]["Clock"];
            node: components["schemas"]["NodeView"];
            maya: components["schemas"]["MayaView"];
        };
        /** StudentName */
        StudentName: {
            /** Display Name */
            display_name: string;
        };
        /** SuggestedLevel */
        SuggestedLevel: {
            /**
             * Cefr
             * @enum {string}
             */
            cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /**
             * Base Cefr
             * @enum {string}
             */
            base_cefr: "PRE_A1" | "A1" | "A2" | "B1" | "B2" | "C1";
            /** Reason */
            reason: string;
            /** Evidence */
            evidence: components["schemas"]["LevelEvidence"][];
        };
        /** TextStimulus */
        TextStimulus: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "dialogue" | "sign" | "message" | "notice" | "timetable";
            /** Speaker */
            speaker: string | null;
            /** Text */
            text: string;
        };
        /** UserView */
        UserView: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "teacher" | "admin";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorldResponse */
        WorldResponse: {
            student: components["schemas"]["StudentName"];
            greeting: components["schemas"]["Greeting"];
            /** Cards */
            cards: components["schemas"]["MissionCard"][];
            snapshot: components["schemas"]["Snapshot"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_world_api_world_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_me_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_classes_api_teacher_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    class_progress_api_teacher_classes__class_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_attempt_api_missions__mission_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The open attempt already existed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateView"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_api_attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_api_attempts__attempt_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_api_attempts__attempt_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_attempts__attempt_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_attempts__attempt_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: {
                gam_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
